- src/com/nisovin/magicspells/castmodifiers/Condition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/OxygenAboveCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/OxygenBelowCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/OxygenEqualsCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/YawAboveCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/YawBelowCondition.java
OxygenAbove/Below/Equals
YawAbove/Below
> Added Modifiers

- src/com/nisovin/magicspells/spells/targeted/TeleportSpell.java
- added relative-offset, accepts vector value (x,y,z)
- added pitch, accepts float value
- added yaw, accepts float value
- added str-cant-teleport, message when the teleport fails
> Updated TeleportSpell:

- src/com/nisovin/magicspells/spelleffects/SpellEffect.java
- added orbit-horiz-offset, sets the start horizontal offset of the orbit (in degrees).
- added orbit-horiz-expand-radius, (float) expands the horizontal orbit radius by that value (required horiz-expand-delay).
- added orbit-horiz-expand-delay, (int) expands the horizontal orbit radius per the defined amount of ticks (required horiz-expand-radius).
- added orbit-vert-expand-radius, (float) expands the vertical orbit radius by that value (required vert-expand-delay).
- added orbit-vert-expand-delay, (int) expands the vertical orbit radius per the defined amount of ticks (required vert-expand-radius).
> Updated Orbit Effect:

- README.md
- src/com/nisovin/magicspells/castmodifiers/Condition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/RainingCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/ThunderingCondition.java
are two different types of weather in minecraft.
Updated README.md to include a link to the Niblexis example github as
well as added a new badge.
> Forked the "storm" modifier into "raining" and "thundering" since they

- src/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- fixed the effect rotation bug
- added hit-air-during(boolean), spell-on-hit-air(string), spell-interval(int) options to make the homing missile cast the spell-on-hit-air when its chasing its target per spell-interval amount of ticks
- added hit-ground(boolean), stop-on-hit-ground(boolean), spell-on-hit-ground(string) options to stop the homing missile when it hits ground and make it cast the spell-on-hit-ground
- added hit-air-after-duration(boolean), spell-after-duration(string) options to cast the spell-after-duration at the missile location when the duration expires
- added relative-offset(vector), modifies the start location
> Updated HomingMissileSpell:

- src/com/nisovin/magicspells/spells/buff/WindglideSpell.java
- velocity - the force of gliding (the more the value is, the further you will travel)
- height - modifies the height location of the gliding
- interval - interval between gliding push, spells and effects
- cancel-on-collision - whether it should turn off the buff when you collide with a wall
- block-collision-dmg - whether it should block the wall collision dmg
- collision-spell - spell to cast at the player's location when the player collides with a wall
- spell - spell to cast at the caster's location while he is gliding
Effect Positions:
- special - plays the effects at the caster's location while he is gliding
> Added WindglideSpell:

- src/com/nisovin/magicspells/volatilecode/VolatileCodeDisabled.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_10_R1.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_11_R1.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_12_R1.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_8_R1.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_8_R3.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_9_R1.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeEnabled_1_9_R2.java
- src/com/nisovin/magicspells/volatilecode/VolatileCodeHandle.java
- added creaturePathToLoc method (will be used for future things)
> Updated Volatile Code:

- src/com/nisovin/magicspells/castmodifiers/Condition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/OnLeashCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/OverBlockCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/UnderBlockCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/VariableStringEqualsCondition.java
**UnderBlock | OverBlock**
**Example** - underblock/overblock grass,3;20 required
Searches 20 blocks over/under an entity for a glass or block id of 3.
**OnLeash**
**Example** - onleash required
Checks if the target entity is on a leash.
**VariableStringEquals**
**Example** - variablestringequals class:archer required
Checks if the variable "class" is archer for the player.
> 4 New Modifiers | UnderBlock/OverBlock, OnLeash, VariableStringIs

- src/com/nisovin/magicspells/spells/targeted/FarmSpell.java
It was a silly one but, there ya go.
> Fixed Spelling Error for Beetroot in FarmSpell

- src/com/nisovin/magicspells/spelleffects/SpellEffect.java
Fixed a bug which existed even in nisovin's version of MagicSpells, it caused all effects with buff position in buff spells to increase each time you have used that buff spell.
> Buff effect position fix!

- src/com/nisovin/magicspells/spells/targeted/ShadowstepSpell.java
Added - relative-offset
Fixed - A bug which caused the player to teleport at his target's location if his target was looking at the ground or sky
> ShadowstepSpell update!

- src/com/nisovin/magicspells/spells/targeted/ForcetossSpell.java
Added - rotation option (float) rotates the toss location (allows you to toss your target to the left or right)
Improved - horizontal-force and vertical-force now accept float values
Fixed:
- a server crash when the forcetoss spell was targeting the caster while he was sneaking
- horizontal-force didn't work if the caster was targeting himself
- damage option didn't work if the forcetoss spell was casted by targeted multi or aoe spells
> Improved ForcetossSpell.

- src/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
> Improved HomingMissileSpell.

- src/com/nisovin/magicspells/spells/instant/LeapSpell.java
Added - rotation option (float) which rotates the leap direction by the defined amount in degrees.
> Improved LeapSpell.

- src/com/nisovin/magicspells/spells/instant/BeamSpell.java
Added:
- gravity
- spell-on-end
- spell-on-hit-ground
- all effects with delayed position will be played at the end of the beam
Fixed:
- y-offset overrides relative-offset only when the default value is different
> Improved BeamSpell.

- src/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
Added:
- projectile-acceleration
- projectile-acceleration-delay
Fixed:
- stop-on-hit-entity bug
> Improved ParticleProjectileSpell.

- src/com/nisovin/magicspells/spells/targeted/StunSpell.java
New spell options:
- interval - interval between teleporting living entities
Changes:
- duration - changed from seconds to ticks
> StunSpell cleanup.

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/volatilecode/ManagerVolatile.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_15_R1/VolatileCode1_15_R1.kt
Adds full 1.15 support to MagicSpells.
> Add 1.15 support

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spells/BuffSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
- core/src/main/java/com/nisovin/magicspells/variables/GlobalVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/PlayerVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/Variable.java
Changes:
- Added skip in Spell#initSubspell().
- Added some changes to support more placeholders in the PAPI MagicSpells Expansion.
- Fix for PlayerMenuSpell.
> Changes for MS PAPI Expansion

- core/src/main/java/com/nisovin/magicspells/commands/CastCommand.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/ParticlesEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/ParticlesPersonalEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
> Added relative-offset and offset to effect positions

- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/PlaceholderAPIDataSpell.java
PAPIDataSpell - Removed deep search for safety, added bracket placeholders
> PAPIDataSpell - fixes

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spells/instant/GateSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/RecallSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/AreaEffectSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
Added spell-on-entity-location for HomingMissileSpell
> Optimizations

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/ActionBarTextEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/EffectLibEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/MinionSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/AreaEffectSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- core/src/main/java/com/nisovin/magicspells/util/ProjectileTracker.java
ParticleProjectileSpell and HomingMissileSpell support direct effectlib effects if you use them with projectile position
> Bugfixes for MinionSpell

- core/src/main/java/com/nisovin/magicspells/util/BlockUtils.java
- core/src/main/java/com/nisovin/magicspells/util/CastItem.java
- core/src/main/java/com/nisovin/magicspells/util/ItemUtil.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItems.java
> Added missing durability materials

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/handlers/RecipeHandler.java
- core/src/main/java/com/nisovin/magicspells/spells/MenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/CraftListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/AreaEffectSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DotSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PainSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ParseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SilenceSpell.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_13_R2/VolatileCode1_13_R2.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_14_R1/VolatileCode1_14_R1.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_15_R1/VolatileCode1_15_R1.kt
* Menu spell `quantity` can be a variable name.
* Added `damage-type` to Pain spell.
* Added `use-proximity` and `reverse-proximity` to AreaEffect spell.
* Added `spell-on-denied-cast`, `spell-on-denied-chat`, and `spell-on-denied-command` to Silence spell.
> Added AOE spell proximity sorting

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/events/MagicSpellsLoadedEvent.java
- core/src/main/java/com/nisovin/magicspells/events/MagicSpellsLoadingEvent.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/ResourcePackListener.java
These changes allow developers to read custom spell files from other directories than the main plugin folder, also refactored ResourcePack passive trigger.
> Expanded API and cleanup

- build.gradle
- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ParticleCloudSpell.java
Added custom-name to ParticleCloudSpell
> Updated shadow plugin

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ArmorStandEffect.java
- Added head-pose to armorstandeffect
- Added mainhand-pose to armorstandeffect
- Added offhand-pose to armorstandeffect
- Added mainhand-item to armorstandeffect
- Added offhand-item to armorstandeffect
- Added custom-name to armorstandeffect
- Added name-visible to armorstandeffect
- Silenced the armorstand in armorstandeffect
> ArmorStandEffect additions

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HasSpellCondition.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/BossBarEffect.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
Readded "variable-max" section to the boss bar effect which was somehow lost in various beta versions. Allows you to define a variable as the max value for a boss bar.
Added "hasspell" modifier which passes if the target has the specified spell.
> Minor Additions

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/BossBarEffect.java
BossBarEffect doesn't allow an empty (progress = 0) or full bar (progress = 1) when using variable progress.
> BossBarEffect doesn't allow an empty or full bar

- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/TimestampMillisecondsVariable.java
Timestamp meta variable in milliseconds.
> Added TimestampMillisecondsVariable

- core/src/main/java/com/nisovin/magicspells/spells/targeted/DotSpell.java
Added options `ignore-armor`, `check-plugins`, `avoid-damage-modification` and `try-avoiding-anticheat-plugins` to DotSpell.
> Added DotSpell options

- core/src/main/java/com/nisovin/magicspells/spells/command/AdminTeachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/BindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ForgetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/HelpSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ImbueSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ItemSerializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/KeybindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ListSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ResetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ScrollSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/SpellbookSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/SublistSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/TeachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/TomeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/UnbindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/OffsetLocationSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/util/ProjectileTracker.java
> CommandSpell API

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/EffectPosition.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/trackers/AsyncEffectTracker.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/trackers/BuffEffectlibTracker.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/trackers/OrbitEffectlibTracker.java
- core/src/main/java/com/nisovin/magicspells/spells/BuffSpell.java
Removed ids from effect positions
> Added `buffeffectlib` and `orbiteffectlib` effect positions

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/ModifierType.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/ChanceCondition.java
- core/src/main/java/com/nisovin/magicspells/listeners/LeftClickListener.java
Additions:
- Added left click cast items.
Changes:
- `castinstead` now stops modifier processing.
- `chance` conditions can now take on double values, rather than only an integer.
> Additions & Changes

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Perm.java
- core/src/main/java/com/nisovin/magicspells/commands/MagicCommand.java
- core/src/main/resources/general.yml
Added /ms taskinfo command which displays info about scheduled plugin and effect tasks.
> Added effect-swipe-interval which cleans finished effectlib effects.

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/OffHandPreciseCondition.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
Modifier OffHandPreciseCondition is activated when caster is holding magic-item in off hand.
> Add OffHandPreciseCondition

- core/src/main/java/com/nisovin/magicspells/spells/passive/FishListener.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/ManaRegenVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/ManaVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/MaxManaVariable.java
- Added `meta_mana`, `meta_max_mana` and `meta_mana_regen` variables.
- Updated `fish` passive trigger and registered it in `PassiveManager`.
> Meta mana variables, fix FishListener

- core/src/main/java/com/nisovin/magicspells/spells/passive/FoodLevelChangeListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/ManaChangeListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/RegainHealthListener.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
- Added `manachange`, `regainhealth` and `foodlevelchange` passive triggers.
> Add `manachange`, `regainhealth` and `foodlevelchange` passive triggers

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spells/TargetedMultiSpell.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_17_R1/VolatileCode1_17_R1.kt
Added pass-targeting for TargetedMultiSpell
> Updated to 1.17.1

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/BowSpell.java
> Fix BowSpell not working with crossbows

- core/src/main/java/com/nisovin/magicspells/spells/passive/DismountListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/MountListener.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
Triggers when entity mounts/dismounts other entity. Ex: mount pig/dismount pig
> Added dismount/mount triggers

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/Modifier.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/ModifierSet.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/ModifierType.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/MultiCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/customdata/CustomData.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/customdata/CustomDataFloat.java
- core/src/main/java/com/nisovin/magicspells/mana/ManaSystem.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/BossBarEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/MenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/PassiveSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ProjectileModifySpell.java
This PR unifies any additional modifier actionVar data to a CustomData class. Additionally, it adds various debug texts for whenever the data is processed.
Gist test: https://gist.github.com/JasperLorelai/08060d5b899216dbf65e7a14f6d2320e
> Refactor how modifier action data is processed

- core/src/main/java/com/nisovin/magicspells/util/ai/PathToGoal.java
Allows spells to path mobs to certain areas. Will be useful in the future.
> Create "PathTo" Goal

- core/src/main/java/com/nisovin/magicspells/spells/passive/AnvilListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/EnchantListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/GrindstoneListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SmithListener.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
- Added `anvil`, `enchant`, `grindstone` and `smith` passive triggers.
> Add several inventory listeners

- core/src/main/java/com/nisovin/magicspells/spells/passive/PrepareEnchantListener.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
- `enchant` passive trigger now activates when an item is enchanted, while `prepareenchant` refers to when enchantment options are being generated for an item.
> Distinguish between enchanting vs preparing enchants

- core/src/main/java/com/nisovin/magicspells/spells/buff/LightwalkSpell.java
With the introduction of the `light` block, the Lightwalk spell could use an update. So, I've removed `material` and added `y-offset` and `block-type` with block data support. This can come in useful as represented by this example: `light[level=6]`.
The default values of this spell have also been changed. Previously it would've been a `glowstone` block, `y-offset: -1`, but now it's `light` block, `y-offset: 0`. The default `allowed-types` now only contains `air`.
> Removed "material", added "block-type" (block data) and "y-offset"

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/AlwaysCondition.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
- core/src/main/java/com/nisovin/magicspells/util/managers/SpellEffectManager.java
- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/util/projectile/ProjectileManagers.java
- Added `always` condition, a more explicit version of `chance 100` for clarity.
- Replaced deprecated usage of `Class#newInstance`.
> Add always condition, cleanup

- build.gradle
- core/build.gradle
- gradle.properties
- shop/build.gradle
Jitpack seems happier with these
Changes included:
- Move versions to gradle.properties
- Publish additional module to trigger multi module access from jitpack
> Artifact coordinates

- build.gradle
- buildSrc/src/main/java/dev/magicspells/gradle/MSJavaPlugin.java
- buildSrc/src/main/java/dev/magicspells/gradle/MSPaperweight.java
- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticlesEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticlesPersonalEffect.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_19_R1/VolatileCode1_19_R1.kt
- gradle.properties
Bumped version to 12.
Added missing mobs from previous updates.
Added sculk-charge-rotation and shriek-delay particle options.
> Initial 1.19 update.

- core/src/main/java/com/nisovin/magicspells/util/Util.java
- Fixes hex color issues in areas that still rely on `Util#colorize(String)`.
> Translate hex codes properly

- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/PlaceholderAPIDataSpell.java
Implemented TargetedEntitySpell interface to PlaceholderAPIData and added bool options: `use-target-variables`, `set-target-variable`, and `set-target-placeholders`.
> Refactor to support targeted entity spells

- build.gradle
- buildSrc/src/main/java/dev/magicspells/gradle/MSPaperweight.java
- core/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- towny/build.gradle
- towny/src/main/java/com/nisovin/magicspells/towny/MagicSpellsTowny.java
Update dependencies
Cleanup for Towny addon.
> Bump version to `13`

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spells/instant/VelocitySpell.java
> Fix power issue in VelocitySpell

- build.gradle
- buildSrc/src/main/java/dev/magicspells/gradle/MSPaperweight.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_19_R2/VolatileCode1_19_R2.kt
- core/src/main/resources/plugin.yml
- gradle/wrapper/gradle-wrapper.properties
> Add `1.19.3` support

- core/src/main/java/com/nisovin/magicspells/spells/targeted/DestroySpell.java
> Fix `horiz-radius` for `DestroySpell`

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spells/PassiveSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/GiveDamageListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/TakeDamageListener.java
> Fix `takedamage` and `givedamage` triggering when final damage was 0.

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/NovaEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/NovaSpell.java
Added blockData variable replacement for `NovaSpell` and `NovaEffect`.
> Added blockData support for `NovaSpell`.

- core/src/main/java/com/nisovin/magicspells/util/ColorUtil.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- core/src/main/java/com/nisovin/magicspells/util/config/FunctionData.java
- Support ARGB hex strings.
- Support more display entity options in `EntityData`.
- Add `ConfigDataUtil` methods for color and nullable numbers.
> Improved display entity support for `EntityData`, ConfigDataUtil additions

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/EntityEffect.java
Added `duration` for `EntityEffect`.
> `EntityEffect` can now play at spell locations.

- core/src/main/java/com/nisovin/magicspells/util/MessageBlocker.java
https://github.com/dmulloy2/ProtocolLib/pull/1601#issuecomment-1151954381
> Fix chat packet cancellation

- core/src/main/java/com/nisovin/magicspells/util/config/CustomFunctions.java
- core/src/main/java/com/nisovin/magicspells/util/config/FunctionData.java
These are the [same functions](https://github.com/elBukkit/MagicPlugin/wiki/Equations#custom-functions-added-by-magic) implemented by EffectLib in the EquationEffect.
> Added custom config data functions

- core/src/main/java/com/nisovin/magicspells/spells/BowSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/RandomSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/HelpSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ImbueSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ItemSerializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/KeybindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ListSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ScrollSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/SublistSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/TomeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/CastAtMarkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/MagnetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/PurgeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/TimeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/UnconjureSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/VariableCastSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/NovaSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ResourcePackSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/RotateSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SilenceSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SummonSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SwitchSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TreeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/VinesSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/VolleySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/GlowSpell.java
- Added more calls to `playSpellEffects`.
- Fixed an issue in `RotateSpell` where a cast would return as failed when `face` was not specified.
> Play spell effects in more areas

- core/src/main/java/com/nisovin/magicspells/spells/buff/MinionSpell.java
Fixes `attack-spell` not being cast if the minion used projectiles.
> fix: Get shooter as damager

- core/src/main/java/com/nisovin/magicspells/spells/targeted/AreaScanSpell.java
- Added the option `scan-modifiers` to `AreaScanSpell`. `scan-modifiers` will now be used instead of `location-modifiers` when checking scanned blocks. `location-modifiers` will now only be used for the initial block to start a scan.
> Use scan-modifiers instead of location-modifiers

- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
Added:
projectile-horiz-offset
projectile-vert-offset
projectile-horiz-spread
projectile-vert-spread
Closes #635
> Added new options to HomingMissileSpell

- core/src/main/java/com/nisovin/magicspells/spells/MenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
- Fixed an issue that allowed dragging items into menus created from `MenuSpell` and `PlayerMenuSpell`.
> Cancel drags in menu

- .github/workflows/build.yml
- Adds a github action that automatically builds and uploads the core plugin on push.
> Add build github action

- build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- nms/v1_20_R3/build.gradle
- nms/v1_20_R3/src/main/java/com/nisovin/magicspells/volatilecode/v1_20_R3/VolatileCode1_20_R3.kt
- settings.gradle.kts
Updated gradle and paperweight.
> Added 1.20.4 support.

- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/mana/ManaSystem.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeDisabled.java
- nms/shared/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeHandle.java
- nms/v1_20_R2/src/main/java/com/nisovin/magicspells/volatilecode/v1_20_R2/VolatileCode1_20_R2.kt
- nms/v1_20_R3/src/main/java/com/nisovin/magicspells/volatilecode/v1_20_R3/VolatileCode1_20_R3.kt
It's now using packets instead of actually  modifying the food bar itself.
> Fix showing mana on the food bar.

- build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- towny/build.gradle
> Effectlib upstream changes + SoundEffect fix.

- .github/ISSUE_TEMPLATE/01-bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
You can find an [example of this here](https://github.com/JasperLorelai/MagicSpells/issues/11). I'm not a fan of the "2 tasks done" label displayed for checkbox elements checked, but the feature is in beta, so I'm hoping GitHub might remove it for forms (?).
> [no ci] Add required bug report form for Issues

- core/src/main/java/com/nisovin/magicspells/events/SpellApplyDamageEvent.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/DamageEmpowerSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/InvulnerabilitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ResistSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ProjectileSpell.java
> Fixed ProjectileSpell failing to hit due to vanilla logic. Added flat-modifier for ResistSpell and DamageEmpowerSpell

- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- correctly check if the targeted block is replaceable
- make the cap-per-player option consistent
> Fix PulserSpell not performing checks on the correct block

- core/src/main/java/com/nisovin/magicspells/Spell.java
> Cast time interrupt spell filter

- build.gradle
- buildSrc/src/main/java/dev/magicspells/gradle/MSPaperweight.java
- core/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- nms/v1_21/build.gradle
- nms/v1_21/src/main/java/com/nisovin/magicspells/volatilecode/v1_21/VolatileCode_v1_21.kt
- settings.gradle.kts
1.21 support.
Removed 1.20.6 support.
> Bump to Beta 16.

- build.gradle
- core/build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Fix EffectLib for 1.21

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/util/MagicConfig.java
- core/src/main/resources/defaults.yml
- Extend defaults to include options from superclasses.
- Default values can now support replacement.
- Added an explanation in `defaults.yml`.
> Refactor defaults.yml

- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/ParticleProjectileTracker.java
Adds back in the step up logic missing from #935.
> Handle stepping up blocks for hug-surface

- core/src/main/java/com/nisovin/magicspells/util/managers/BuffManager.java
This will not fix all of the many issues with stale entities and buff spells, but should prevent stale entities from causing issues with no magic zones.
> Refresh entity in buff manager if possible

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticleCloudEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ThrowBlockSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/FireballSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ParticleCloudSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnTntSpell.java
> Attach ProjectileSource

- core/src/main/java/com/nisovin/magicspells/spells/targeted/ParticleCloudSpell.java
> Properly check if custom name is null

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Perm.java
- Remove permissions on reload.
- Bulk add permissions to avoid long initial load times from adding permissions.
> Bulk add permissions, cleanup

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/DodgeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/FrostwalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/MinionSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/WaterwalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/WindwalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/DowseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/GateSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/PhaseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/RecallSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/BlinkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/EntombSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/FlySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/GripSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/RewindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ShadowstepSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/StunSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SummonSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SwitchSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TeleportSpell.java
- core/src/main/java/com/nisovin/magicspells/util/DelayableEntity.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/CoordPitchVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/CoordXVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/CoordYVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/CoordYawVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/CoordZVariable.java
> Try to retain passengers and vehicles with most TP calls
