TheComputerGeek2/MagicSpells

- src/com/nisovin/magicspells/spells/targeted/OrbitSpell.java
- added start-horiz-offset, sets the start horizontal offset of the orbit (in degrees)
- added spell-on-hit-ground, casts that spell when the orbit hits any ground block
- added stop-on-hit-ground, (boolean) if set to true, removes the orbit when it hits any ground block
- added spell-on-hit-entity, casts that spell when the orbit hits any entity
- added stop-on-hit-entity, (boolean) if set to true, removes the orbit when it hits any entity
- added hit-radius, (float) sets the horizontal hitbox radius (used for spell-on-hit-entity and stop-on-hit-entity)
- added vertical-hit-radius, (float) sets the vertical hitbox radius (used for spell-on-hit-entity and stop-on-hit-entity)
- added can-hit, (string list) determines what should be counted as "entity" (used for spell-on-hit-entity and …
> Updated OrbitSpell:

- src/com/nisovin/magicspells/spells/targeted/ParseSpell.java
- src/spells-regular.yml
The parse spell allows expected variables to be transferred into other variables.
While this was mainly made to bridge string variables and modifiers, It has much more potential uses than that and will most likely be expanded in the future!
Also added a header to Spells-Regular.yml to help newcomers get integrated into the community.
> Introduced the targeted.ParseSpell

- src/com/nisovin/magicspells/castmodifiers/Condition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/VariableCompareCondition.java
Compares two string/integer variables against one another. Passes if they match and fails if they don't.
Acceptable format: `Variable1:Variable2`
This modifier is only meant to be used as a caster orientated modifier. To use against targets, see `variablematches`
> Introduced "variablecompare" modifier.

- src/com/nisovin/magicspells/spells/buff/MinionSpell.java
Added:
- potion effects
- attributes
- armor
- item in main hand
- item in off hand
- armor drop chance
- custom name (%c replaces the caster's name, supports color codes)
- spawn offset which modifies its spawn location
- spell on spawn
- spell on attack
- spell on death
- follow range
- follow speed
- max distance
- health
- max health
- power affecting health
- minion target list
- zombie baby state
Improved Behavior:
- when the target of the minion dies, he will follow his owner if he moves from his current location
- after being damaged by any mob/player, the minion will focus the damager
- when two mobs/players are attacking the caster, the minion will always focus the closest damager
- when the minion doesn't have a target and someone will damage him, he will focus the damager
- …
> Improved MinionSpell

- build.gradle
- src/com/nisovin/magicspells/castmodifiers/Condition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/GriefPreventionIsOwnerCondition.java
- src/com/nisovin/magicspells/castmodifiers/conditions/VariableCompareCondition.java
- src/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- src/plugin.yml
Magicspells now supports GriefPrevention modifiers. Currently only "griefpreventionisowner" is present but more will appear soon. Checks if the target/player is the owner of the current claim.
- `griefpreventionisowner (action)`
Condition "variablecompare" now supports greater than + less than.
- `variablecompare var1<var2`
- `variablecompare var1>var2`
- `variablecompare var1:var2`
Homing Missile errors should quiet down now.
**Coming soon**: OpenTerrainGeneratorBiome modifier!
> Added GriefPrevention Support + Variablecompare updates

- src/com/nisovin/magicspells/spells/instant/ConjureSpell.java
If a kill passive tries to conjure an item at the death location of an entity, this allows it to target the entity in the specific event it dies and conjure the items at their location accordingly.
> Conjure Spell change to support kill passives

- src/com/nisovin/magicspells/spells/targeted/MaterializeSpell.java
| Materialize Spell | - New Features
**area** | Define an area of blocks to materialize
Area must support a block as its geometrical center!
**height** | Define the area's height to materialize
fall-height | Change how high falling blocks fall from
use-pattern - enables the use of patterns
patterns - define a list of blocks to be used per row.
If they are more rows than pattern lists, it will repeat
It will go through until the pattern lists are all used up
restart-pattern-each-row - Normally, the pattern continues through if it has been reset. 41,42 pattern will continue within a 3x3 becoming...
**41,42,41
42,41,42
41,42,41**
This options makes it...
**41,42,41
41,42,41
41,42,41**
randomize-pattern - Literally randomizes a row's pattern 
Thanks once again, Shadoward12 for the inspiration …
>  New Materialize Spell Features

- src/com/nisovin/magicspells/spells/ArrowSpell.java
- src/com/nisovin/magicspells/spells/BowSpell.java
Right now, bow spells don't care about cooldowns nor reagents. Additionally, no information is shown to the user when bow/arrow spells are on cooldown or missing reagents. This PR addresses both of these.
> Properly handle cooldowns and reagents for bow spells

- src/com/nisovin/magicspells/spells/targeted/NovaSpell.java
Spell Options:
type: blocktype(string)
relative-offset: relativeOffset(x,y,z)
spell: spell casted when a new wave forms(string)
spell-on-end: requires remove-previous-blocks to be set to false, casts it when all block waves are gone(string)
spell-on-wave-remove: requires remove-previous-blocks to be set to true, casts on the previous removed wave(string)
radius: radius of the nova(int)
start-radius: start radius of the nova(int)
height-per-tick: height per new wave(int)
expand-interval: interval between forming a new wave(int)
expanding-radius-change: how big should each wave be, in blocks(int)
visible-range: visible range of the nova(double)
point-blank: point blank(boolean)
circle-shape: whether the nova should be a circle or a square(boolean)
remove-previous-blocks: whether it should …
> Added new NovaSpell.

- src/com/nisovin/magicspells/spells/targeted/RotateSpell.java
Example Rotate Spell Config
RotateSpell:
spell-class: ".targeted.RotateSpell"
rotation: 10
rotation-pitch: 0
affect-pitch: false
mimic-direction: false
face-target: false
face-caster: false
Notes: rotation only affects the Yaw value of an entity
New Features:
rotation-pitch: adds/remove pitch of an entity
affect-pitch: a safe flag for if you want the pitch unaffected. This must be true for rotation-pitch to work
mimic-direction: mimics the direction of the target/caster so that the target/caster faces in the same relative direction.
face-caster: forces the target to face the caster
face-target: forces the caster to face the target
Cool Ideas:
You can make a cut scene with the new rotate spell features. Simple set face-target to true and have a mob be followed as it moves across a screen. …
> Rotate Spell | affectPitch, Face and Mimic Options

- src/com/nisovin/magicspells/spells/instant/ForcepushSpell.java
- src/com/nisovin/magicspells/spells/instant/LeapSpell.java
- src/com/nisovin/magicspells/spells/instant/VelocitySpell.java
- src/com/nisovin/magicspells/spells/targeted/ForcebombSpell.java
- src/com/nisovin/magicspells/spells/targeted/ForcetossSpell.java
Spells affected:
Forcepush, ForceToss, ForceBomb, Leap, Velocity.
All these spells have an add-velocity-instead option that adds that force to the target instead of setting it.
If I had 3 velocity to the right and I add 2 to the left. I will move slower.
Perfect for black-hole or gravity spells. This option is false by default.
> Force, Leap, Velocity spells can add velocity instead of set.

- core/src/main/java/com/nisovin/magicspells/spells/targeted/CombustSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/FireballSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ForcetossSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/GeyserSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/LightningSpell.java
Almost any time MagicSpellsEntityDamageByEntityEvent is called, MagicSpells checks the entity to see if it's a player. However the constructor for this event accepts entities and the name of the event is misleading. There is no reason that MagicSpells should check for this.
This PR  removes that check and calls the event on any entity like it should.
> Call MagicSpellsEntityDamageByEntityEvent for any entity

- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
Added a `marker` option to Totem spells. Bool, false by default.
> TotemSpell - added marker property

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/VariableStringEqualsCondition.java
Example: `variablestringequals stringVar:null (action)`
Translates "null" value of the string to "", so that comparison with an empty variable could be possible.
> VariableStringEqualsCondition - Allowed null comparison

- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
If `totem-name` was specified, CustomNameVisibility was fixed to true. This property makes CustomNameVisibility value depend on it.
> TotemSpell - added totem-name-visible property

- core/src/main/java/com/nisovin/magicspells/castmodifiers/Condition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/SlotSelectedCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SlotSelectSpell.java
SlotSelectedCondition - `slotselected (op)(value)`
SlotSelectSpell (Targeted Entity Spell):
- `slot` - can be a number (Integer) or a variable name (String).
- `ignore-slot-bounds` (Boolean, false) - A warning which can optionally be turned off if the outcome is intended.
> New condition "slotselected" & New spell "SlotSelectSpell"

- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
New Targeted Entity spell:
- `title` (String) - Supports color codes, variable replacement, and replaces `%a` with caster's username.
- `delay` (Integer, 1)
- `radius` (double, 0) - When set to 0, shows all online players, otherwise all in radius.
- `stay-open` (Boolean, true) - When a player is selected in the menu, this defines if the menu should close.
Name of all player heads in the menu and the item lore of them. Supports color codes,
variable replacement, replaces %a with caster's name, and %t with target's name:
- `skull-name` (String)
- `skull-lore` (String List)
- `skull-name-range` (String) - Skull name displayed if the player is out of range.
- `skull-name-offline` (String) - Doesn't support `%t` replacement.
- `spell-offline` (String) - Spell casted if selected player is …
> New Spell: PlayerMenuSpell

- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
Also renamed properties:
- `spell-invalid` => `spell-offline`
- `skull-name-invalid` => `skull-name-offline`
> PlayerMenuSpell - Fixed subspell initialisation

- core/src/main/java/com/nisovin/magicspells/spells/instant/ProjectileSpell.java
This PR adds an option to ProjectileSpell that allows explosives (fireball, tnt, wither skulls, etc.) to spawn fire (or not) when they explode.
> Add incendiary option to ProjectileSpell

- core/src/main/java/com/nisovin/magicspells/RightClickListener.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/CarpetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ReplaceSpell.java
* You can list "all" in `replace-blocks` in order to whitelist all blocks for replacement.
* Added `replace-blacklist`.
* Blocks created by this spell are now removed on plugin reload.
* Added debug message for invalid items specified for any cast items.
* Fixed bug with **right click cast item(s)** where if the specified item is invalid, it could cause the "spell1 has same right click cast item specified as spell2" to be sent even if the item strings are unique.
> Bugfix and Additions

- core/src/main/java/com/nisovin/magicspells/castmodifiers/Condition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HasScoreboardTagCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
- docs/spigot_page.md
- Added the docs folder to hold any sort of important document for magicspells including the spigot page layout. More files will be added into this folder at a later date.
- Added `HasScoreboardTag` condition which supports variable replacement. Checks if the target has a scoreboard tag embedded in their NBT.
- Fixed positioning of totem spells when spawning from projectile based spells. They now spawn at precise locations instead of block based locations. This positioning can be used through `center-stand: false` (defaults `true`)
- Totem spells now spawn with the tag `MS_Totem` which allows other plugins a easy way to sense them as well as some user level interactions.
> Docs folder, HasScoreboardTag, and TotemSpell fixes

- core/src/main/java/com/nisovin/magicspells/spells/passive/PassiveTrigger.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/PotionEffectListener.java
Added a new passive trigger for PotionEffect events.
Parameters include effect names, actions, and causes.
Each parameter can be a comma-separated list of valid options, or a wildcard (*) to accept all options.
Instant potion effects seem to only work when eating/drinking, and fire being added and removed simultaneously.
If multiple potion effects are affected by one instance - such as drinking a potion with multiple effects or a bucket of milk - this event will fire separately for each effect.
> Added PotionEffect passive trigger

- core/src/main/java/com/nisovin/magicspells/spells/targeted/DataSpell.java
When support was added for missing DataLivingEntity elements, the spell was changed to only get data elements from the caster. As such, regardless of if target-self is true, the spell only targets self.
> DataSpell getting data from caster instead of target

- core/src/main/java/com/nisovin/magicspells/Spell.java
Durability costs don't work - when you do getItemMeta(), you get a clone of the item's meta. So, when you change the durability damage on that clone, it doesn't change the original item's meta.
> Durability costs don't work

- core/src/main/java/com/nisovin/magicspells/spelleffects/BossBarEffect.java
Currently, titles for bossbar effects don't support variable replacement, unlike other effects (such as action bar text effects).
> Bossbar effect titles don't support variable replacement

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/volatilecode/ManagerVolatile.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodePaper.kt
Adds a volatile code handler for Paper to rely on API methods that Paper has to offer that Spigot does not have. Should allow for some volatile code methods to work across server updates for users using Paper. This is _only_ used if Paper is detected as the server software being ran, and falls-back to the current volatile code handler for anything not handled by Paper.
> Add volatile code handler for Paper

- core/src/main/java/com/nisovin/magicspells/spells/passive/PassiveTrigger.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SwimListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TagEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/util/ValidTargetList.java
- core/src/main/java/com/nisovin/magicspells/variables/SpecialVariables.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/TimestampDaysVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/TimestampHoursVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/TimestampMinutesVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/TimestampSecondsVariable.java
- `meta_timestamp_days`
- `meta_timestamp_hours`
- `meta_timestamp_minutes`
- `meta_timestamp_seconds`
These special variables get the current timestamp and allow you to compare it later. This greatly increases the ability to measure time over long periods without ticking (even if the server goes offline or there is no players).
- `castermount`
- `casterpassenger`
- `mount`
- `passengers`
- `mobtarget`
You can now specifically target mounts and passengers as well as the **casters** mount or passenger. This should greatly increase functions for some RPG servers with healing spells that also want to heal your mount.
The `mobtarget` targeter allows a mob to specifically target its current target. While there are other methods of doing this in MS, this reduces spell count. Only works with mob …
> Decent amount of changes

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/handlers/RecipeHandler.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/BossBarEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/NovaEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/MenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/MaterializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ParseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ReplaceSpell.java
- core/src/main/java/com/nisovin/magicspells/util/MagicConfig.java
- core/src/main/java/com/nisovin/magicspells/util/SpellAnimation.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/util/managers/BossBarManager.java
- core/src/main/java/com/nisovin/magicspells/variables/Variable.java
- core/src/main/java/com/nisovin/magicspells/variables/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeDisabled.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeHandle.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodePaper.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_13_R2/VolatileCode1_13_R2.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_14_R1/VolatileCode1_14_R1.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_15_R1/VolatileCode1_15_R1.kt
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_16_R1/VolatileCode1_16_R1.kt
The Menu spell `slots` property was added to set the defined item to all listed slots. It'll be prioritised over the `slot` property.
The Menu spell also had a long-term bug which was recently further exposed by accident. To set the scene, if two or multiple menu spells exist with the same title, all instances of their InventoryClick events would activate. If the item clicked has the same `options` key, it would trigger on all instances. The issue here was indentifying which menu's spell the item belongs to. Now I'm not particularly sure if this solution is good or not - in the real title I'm storing the internal spell name to help indentify the option item origin. I'm sending packets to update the menu title to the client.
> Custom Recipes and bugfixes

- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
setting silenced: true 
will prevent sound from playing when the armorstand is created/modified.
> Added "silenced" option for the TotemSpell.

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/HitArrowListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/MissArrowListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/PassiveTrigger.java
The main improvement here is a configuration option to switch spell cycle mouse buttons when the player is holding a bow or a crossbow ("reverse-bow-cycle-buttons"), but also adds another configuration option to disable the spell cycle when the player is sneaking while holding a bow ("bow-cycle-spells-sneaking").
In addition there are HitArrowListener and MissArrowListener passive spell trigger implementations.
> Improved bow support

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Perm.java
- core/src/main/java/com/nisovin/magicspells/commands/MagicCommand.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/VariableCastSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HealSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/StunSpell.java
- core/src/main/java/com/nisovin/magicspells/util/ProjectileTracker.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/AltitudeVariable.java
* Added `magicspells.command.cast.power` permission which allows users to use the power command parameter (`-p:`).
* Added `stun-monitor` and `stun-body` toggles to StunSpell.
* Added `use-target-location` to StunSpell which controls whether the target should be teleported to the location they were at when they were targeted (previous and default behaviour) or if the location they moved **from**.
* Added `disallowed-ground-materials` to ParticleProjectileSpell - the ground blocks the projectile should ignore.
* Added `heal-percent` to HealSpell.
* Fixed the null error which occurs when the VariableCastSpell is cast.
* Fixed altitude meta variable returning wrong values.
> Small additions

- core/src/main/java/com/nisovin/magicspells/listeners/VariableListener.java
Currently, variable mods process all the modifications to each variable sequentially, rather than the order the mods were written.
For example, if this was the variable mods:
```yml
variable-mods-cast:
- offset =10
- var1 +offset
- offset =20
- var2 +offset
```
20 would be added to both `var1` and `var2`, instead of 10 to `var1` and 20 to `var2`. All the mods for the variable `offset` are processed first, then `var1`, then `var2`.
> Variable mods are now processed in order

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HasItemCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HoldingCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/OffhandCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/WearingCondition.java
Certain conditions only check for legacy material names, which means they do not work with any of the materials added after the 1.13 update.
> Certain conditions don't work with 1.13+ materials

- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItems.java
This most noticeably improves the runtime for spells that trigger modifiers that check for items in quick succession.
I'm not sure if we want to cache the other related methods or if we want to have some sort of expiry, but this is a start.
> Implement caching for `getMagicItemDataFromItemStack`

- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellCastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellCastedListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellSelectListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellTargetListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellTargetedListener.java
SpellFilter support for the `spellcast`, `spellcasted`, `spelltarget`, `spelltargeted` and `spellselect` passive triggers. Tags are prepended by `tag:` and blacklisted members are prepended by `!`.
> Spell filter support for passive triggers

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/Subspell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellCastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellCastedListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellSelectListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/SpellTargetedListener.java
- Messages for invalid spell cast states are now sent when using a cast mode of full.
- Delayed spell casts using `cast-time` now:
- No longer send interrupt messages when the spell has already casted.
- Properly unregister event listeners when interrupted in all cases.
- Interrupt when a player moves.
- Spell filters on `spellcast`, `spellcasted`, `spelltarget`, `spelltargeted` and `spellselect` passive triggers should no longer produce an error when the filter is empty.
> Cast mode and time fixes

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HasScoreboardTagCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/JumpListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DestroySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ReplaceSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/GlowSpell.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/util/ai/LookAtEntityGoal.java
* Fixed variable replacement on `hasscoreboardtag` modifier condition (var).
* Destroy spell calls block break events.
* Replace spell will now store BlockData instead of Material.
* Added Glow Spell (Targeted Entity Spell, `.targeted.ext.GlowSpell`):
* `toggle` - (Boolean, false)
* `duration` - (Integer, 0) - In server ticks. 0 defines everlasting duration.
* `client-side` - (Boolean, false)
* `async` - (Boolean, true)
* `update-period` - (Integer, 10) - In server ticks. Defines update interval of colors. Should be greater than 0 for multiple colors.
* `colors` - (String list, white) - Should be a list of Chat Colors, but you could list just one.
* The `jump` passive trigger is now cancellable. Note the disclaimer:
> Cancelling this event causes the entity to be teleported back to the …
> Bugfix & Refactor

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/DataCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/SpellSelectedCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/UnconjureSpell.java
- core/src/main/java/com/nisovin/magicspells/util/SpellReagents.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
- Added SpellSelectedCondition - accepts a comma separated list of spells and spell tags. Tags are prepended by `tag:`, and blacklisted elements are prepended by `!`. Passes if caster/target have a spell selected that matches the supplied filter.
- Added DataCondition - checks if the specified data element is lesser than, greater than or equal to the value supplied. `__` can be used to substitute for spaces in the value. Supports variable replacement, including targeted variable replacement using `%castervar` and `%targetvar`.
- `MagicItemData` used for checking reagents or in UnconjureSpell now automatically ignore amount when matching.
> SpellSelectedCondition & DataCondition

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/BowSpell.java
- core/src/main/resources/general.yml
Bugfixes:
- `use-bow-force` was accidentally removed.
- Casting triggered when shooting a bow now uses the bow that was shot from, instead of the item in the caster's mainhand.
Additions:
- Added option `cast-bound-bow-spells-from-offhand`. Disables casting triggered by shooting a bow in the offhand.
- Added option `deny-offhand` to `BowSpell`. Disables casting a `BowSpell` with a bow in the offhand.
- Added option `require-bind` to `BowSpell`. When `require-bind` is true, a `BowSpell` can only be cast when the spell is cast from a bow that has the `BowSpell` as its currently selected spell. `BowSpell` now uses already existing option `bindable` to determine if the spell is bindable, and is by default `false`.
> BowSpell additions

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/util/TxtUtil.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- `Util#setSkin` did not properly change the player's skin.
- Removed redundant utility method `TxtUtil#escapeMatcher`, as it can be replaced with `Matcher#quoteReplacement`.
> SkinSpell bugfix

- core/src/main/java/com/nisovin/magicspells/spells/targeted/CleanseSpell.java
- Remove unnecessary potion effect addition in `CleanseSpell`, which caused flickering potion effects.
> CleanseSpell cleanup

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/MultiCondition.java
- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/util/BlockUtils.java
Bugfixes:
- No longer cast on animate with bows if option `reverse-bow-cycle-buttons` is `true`.
- No longer cast on animate if the player has an inventory open (such as when opening or dropping items from containers).
- `MultiCondition` did not send modifier fail strings.
- `MultiCondition#check(LivingEntity, Location)` is now properly implemented.
Additions:
- Added more blocks to the list of interactable blocks in `CastListener`.
- `spell-on-break` in `PulserSpell` no longer needs to be a `TargetedLocationSpell`.
- New `MultiCondition` pass condition, `NONE`. Passes if none of the modifier checks pass.
> Bugfixes & Additions

- core/src/main/java/com/nisovin/magicspells/util/MobUtil.java
- Namespace key works for all current spawn egg material types. Type name fails for mobs such as mooshrooms.
> Use namespace key instead of type for spawn egg items

- core/src/main/java/com/nisovin/magicspells/Subspell.java
Currently, subspells with a specified delay of 0 are casted immediately, instead of being scheduled with a delay of 0.
> Add ability to cast subspells with a delay of 0

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/events/BuffEndEvent.java
- core/src/main/java/com/nisovin/magicspells/events/BuffStartEvent.java
- core/src/main/java/com/nisovin/magicspells/spells/BuffSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/GlowSpell.java
- core/src/main/java/com/nisovin/magicspells/util/managers/BuffManager.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/BedCoordXVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/BedCoordYVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/BedCoordZVariable.java
* Added `BuffStartEvent` and `BuffEndEvent`.
* The Glow spell has been refactored to use the [GlowAPI](https://github.com/metalshark/GlowAPI/) plugin. Removed `async`, `update-period`, and `colors` properties, added `visible-to-target` and `color`.
* Glow Spell (Targeted Entity Spell, `.targeted.ext.GlowSpell`):
* `toggle` - (Boolean, false)
* `duration` - (Integer, 0) - In server ticks. 0 defines everlasting duration.
* `client-side` - (Boolean, false)
* `visible-to-target` - (Boolean, false)
* `color` - (String, white) - [List of colors](https://github.com/metalshark/GlowAPI/blob/master/src/main/java/org/inventivetalent/glow/GlowAPI.java#L74).
> Refactored GlowSpell using GlowAPI

- core/src/main/java/com/nisovin/magicspells/spells/TargetedMultiSpell.java
Causes issues if attempting to hard cast targeted spells in a TargetedMultiSpell (such as when you want to target self).
> Don't fail TargetedMultiSpell if hard casted spell returns NO_MESSAGES

- core/src/main/java/com/nisovin/magicspells/spells/buff/FlamewalkSpell.java
Currently the compatibility event fired for `check-plugins: true` lists the caster as the targeted entity.
> Fix MagicSpellsEntityDamageByEntityEvent for FlamewalkSpell

- core/src/main/java/com/nisovin/magicspells/spells/BowSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/EquipListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/UnequipListener.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
- `BowSpell` currently stops processing all `spell-on-hit-ground` if one of the spells associated with the arrow has their `SpellTargetLocationEvent` cancelled.
- Added `equip` and `unequip` passive triggers.
> BowSpell bugfix, add equip and unequip passive triggers

- core/src/main/java/com/nisovin/magicspells/spells/targeted/RewindSpell.java
- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/AttributeVariable.java
- `RewindSpell` attempts to use the mana handler even when the internal mana system is disabled, causing a `NullPointerException`.
- Added meta variables such as `meta_attribute_generic_armor` for the value of attributes. Current meta variables only allow you to check/modify their base value.
> Add meta variables for attribute value, fix issue with RewindSpell

- core/src/main/java/com/nisovin/magicspells/spells/targeted/StunSpell.java
Previous calculation rounded down by second, instead of milliseconds.
> Properly calculate duration for StunSpell

- core/src/main/java/com/nisovin/magicspells/spells/instant/MagnetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/CombustSpell.java
- `MagneticSpell` no longer plays spell effects if it isn't cast on `SpellCastState.NORMAL`.
- `CombustSpell` now supports fractional damage values.
> MagneticSpell, CombustSpell bugfixes

- core/src/main/java/com/nisovin/magicspells/util/AttributeUtil.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemData.java
Class fits being a record, and is more concise being grouped with the only method that uses it.
> Move AttributeModifierData to a local record

- core/src/main/java/com/nisovin/magicspells/Subspell.java
Passes the power along from the `SpellCastEvent` to the `SpellTargetEvent` and `SpellLocationEvent`, and uses the power and targets from the respective events.
> Get power and targets after calling events

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/LoopActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/OwnedLoopActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/TargetedSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/CleanseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/LoopSpell.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeDisabled.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeHandle.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_18_R1/VolatileCode1_18_R1.kt
Additions:
- Added `LoopSpell`. Options:
- `delay` - How long, in ticks, before the loop starts. Default: 0.
- `duration` - How long, in ticks, the loop will last. If less than or equal to 0, the loop will last indefinitely unless `iterations` is specified. Default: 0.
- `interval` - How long, in ticks, the interval between casting the `spells`. Default: 20.
- `iterations` - How many total iterations the loop will do. If less than or equal to 0, the loop will last indefinitely unless `duration` is specified. Default: 0
- `y-offset` - Vertical offset when casting at a location.
- `targeted` - If `true`, depending on `require-entity-target` and `point-blank`, the loop will target an entity or location. If `false`, `spells` will be casted without an entity or location target. Default: …
> Add LoopSpell

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/commands/MagicCommand.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/MinionSpell.java
- core/src/main/java/com/nisovin/magicspells/util/MobUtil.java
- core/src/main/resources/general.yml
- Added `error-log-limit` option. Defaults to -1. When greater than 0, deletes old errors to ensure the `errors` folder has at most `error-log-limit` number of files.
- Reverted minimessage version to `4.2.0` due to incompatibilities with current paper versions.
- `MinionSpell` now requires the entity type to be a `Mob` instead of a `Creature`.
> Add `error-log-limit` option, revert to previous minimessage version, extend MinionSpell to Mob instead of Creature, fix issue with /ms resetcd

- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/spells/targeted/RiptideSpell.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeDisabled.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeHandle.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/v1_18_R2/VolatileCode1_18_R2.kt
- Old legacy color code support no longer functions with new MiniMessage deserializer. Instead, old color codes are converted into MiniMessage format, and then serialized.
- Updated volatile code handler. `net.minecraft.world.entity.LivingEntity#startAutoSpinAttack(int)` was relocated to `net.minecraft.world.entity.player.Player#startAutoSpinAttack(int)`, so `VolatileCodeHandle#startAutoSpinAttack(LivingEntity, int)` was updated to `VolatileCodeHandle#startAutoSpinAttack(Player, int)` accordingly.
> Update to 1.18.2

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/AdvancementCondition.java
- Allow keys with namespaces other than `minecraft` and `magicspells` for use in `AdvancementCondition`.
> Allow all namespaced keys for advancements

- README.md
- core/src/main/java/com/nisovin/magicspells/spells/TargetedSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DotSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DrainlifeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PainSpell.java
* Fix for damage spells not calling `LivingEntity#setLastDamage` when dealing artificial damage (`ignore-armor`).
* Call SpellTargetEvent when self-targeting.
* Updated README ([Preview](https://github.com/JasperLorelai/MagicSpells))
> Fixes & Update README.md

- core/src/main/java/com/nisovin/magicspells/listeners/MagicChatListener.java
Prevents an issue with incantations caused by casting a spell asynchronously from the result of an `AsyncChatEvent`.
> Schedule cast as sync task

- core/src/main/java/com/nisovin/magicspells/spells/buff/ArmorSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/HasteSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/InvisibilitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/LightwalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ManaRegenSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/MinionSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ReachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/SeeHealthSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/StonevisionSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/WaterwalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/WindwalkSpell.java
- Return false instead of true when a buff cannot be cast on a non-player entity.
- Check if an entity's equipment is null before attempting to cast `ArmorSpell`.
> Return false if buff cannot be cast on a non-player entity

- core/src/main/java/com/nisovin/magicspells/spells/targeted/PasteSpell.java
- `y-offset` is now also applied when casting at a location, instead of only when casting directly.
> Fix issue with y-offset option in PasteSpell

- core/src/main/java/com/nisovin/magicspells/spells/BowSpell.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemData.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemDataParser.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItems.java
- Added `bow-items`, `ammo-items`, `disallowed-bow-items` and `disallowed-ammo-items` options to `BowSpell`. `bow-items` and `ammo-items` are whitelist magic item filters for the bow and ammo used in a `BowSpell`, respectively. `disallowed-bow-items` and `disallowed-ammo-items` are correspondingly blacklist magic item filters.
- Added `strict-enchants` and `strict-enchant-level` options to magic items. Both options are `true` by default. When a magic item with `strict-enchants: false` is used to match an item, enchantments other than those specified on the magic item no longer cause the match to fail. With `strict-enchant-level: false`, items being matched require at least the level of enchantments specified on the magic item, rather than the exact level.
> Add new options to BowSpell and Magic Items

- core/src/main/java/com/nisovin/magicspells/spells/BuffSpell.java
- Fixes issue with checking target list when `targeted: false`.
> Move valid target list check in BuffSpell

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/OnBlockCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PotionEffectSpell.java
- core/src/main/java/com/nisovin/magicspells/util/ConfigReaderUtil.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- `onblock` modifier can now be used as a location modifier.
- Swapped order of `ambient` and `hidden` options in the string format for `PotionEffectSpell`.
- Fixed issue where `hidden` option was by default `true` in the string format for `PotionEffectSpell`.
- Readded the `targeted` option to `PotionEffectSpell`.
- The `icon`, `hidden` and `ambient` options in `PotionEffectSpell` now support variable replacement.
- Added section format for `potion-effects` in  `PotionEffectSpell`. All of the options for the section style allows for variable replacement. The following are all equivalent:
```yml
test:
spell-class: ".targeted.PotionEffectSpell"
potion-effects:
- speed 100 4 false false true
- {type: speed, duration: 100, strength: 4, ambient: false, hidden: false, icon: true}
- type: speed …
```
> Allow onblock for location modifiers, section format for PotionEffectSpell

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ArmorStandEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/EntityEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- Fixed an issue where `main-gene` was used instead of `hidden-gene` for setting a panda's hidden gene.
- Attributes/options of entities spawned with `EntityData` are now applied before the entity is spawned.
> Cleanup, apply attributes before spawning entity

- core/src/main/java/com/nisovin/magicspells/util/itemreader/DurabilityHandler.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemData.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemDataParser.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItems.java
- Added `strict-durability` option. When `strict-durability: false`, magic items being matched instead only have to have at most the same durability damage as configured, instead of exactly the same.
- When parsing a magic item using the string format, a pre-existing magic item can now be used in place of the material type to use it as base reference for options.
> Magic item additions

- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- Check if the hand animating is the main hand if `cast-on-animate: true`.
- Apply global cooldown after a player drops an item to prevent casting when `cast-on-animate: true`.
> `cast-on-animate` improvements

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/CreatureTargetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DestroySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DummySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- Fixed an issue where `EffectPosition.CASTER` would not be played in certain instances where a spell was casted at an entity from a location. Note: effects played in `EffectPosition.CASTER` now play at the caster's location, not the `from` location as was in older versions.
- Refactored `CreatureTargetSpell` to be an instant spell, as the spell does not use a target. Still located in the `targeted` package to maintain compatibility.
> Effect bugfix, CreatureTargetSpell refactor

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/CustomNameCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/DataCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HasScoreboardTagCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/customdata/CustomDataFloat.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/TitleEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/ExternalCommandSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/MenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/TargetedSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ConjureBookSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/DowseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ThrowBlockSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ChainSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/LoopSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TagEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/PlaceholderAPIDataSpell.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/util/VariableMod.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- core/src/main/java/com/nisovin/magicspells/util/config/FunctionData.java
- core/src/main/java/com/nisovin/magicspells/util/config/StringData.java
- Introduces support for PlaceholderAPI in replacement supporting options.
- Fixes an issue where the `can-target` of `ChainSpell` was improperly checking the original target instead of the chained target.
- Allow casting a non-targeted `spell` in `ChainSpell`.
> PlaceholderAPI support, ChainSpell bugfix

- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/EffectLibLineEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/SmokeTrailEffect.java
Add `start-location-height-offset` and `end-location-height-offset` for `line/trail` effect position Refactored `max-distance` option for `line/trail` effect to cut the effect after the defined distance was reached instead of stopping it entirely.
> Fix effect rotations for `line/trail` effect position.

- core/src/main/java/com/nisovin/magicspells/spells/PlayerMenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/util/MenuData.java
SpawnEntitySpells were spawning in mobs with empty nametags, instead of no nametag at all. Fixed it by defaulting to null instead of "".
PlayerMenuSpells didn't work in games with more than 54 players in it. Changed the spell so that if the player count is over 50 it adds "next tab" and "previous tab" buttons
Added a config to SpawnEntitySpells to customize whether the default attack damage is canceled when using an AttackSpell (old behavior was always true)
Changed spawned entity behavior to obey the ValidTargetList when picking targets (old behavior was always ignore caster)
> Spawnentity nameplates now hidden when unused

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/VelocityActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/WindwalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/VelocitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/BuffListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/FlySpell.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
* `FlySpell`:
* Fixed spell not allowing flight.
* Added `set-flying` bool toggle (def: `true`).
* `WindwalkSpell`:
* Fixed `launch-speed` being interrupted.
* Added `enable-max-y` bool toggle (def: `true`). (It used to instead depend on `max-y > 0`.)
* Spell restores fly speed after ending.
* Added `always-fly` bool toggle (def: `false`).
* `buff` passive spell trigger:
* Spells will now turn off when the player is in Spectator or Creative and will turn on otherwise.
* Forgetting all spells will turn off buffs.
* Non buff `spells` will be cast when the buffs are turned on.
* Added `velocityactive` modifier condition,
> Changes to "FlySpell", "WindwalkSpell", and "buff" trigger

- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- Fixed an issue where `HomingProjectileSpell` where a projectile at the same location as its target would have `NaN` velocity.
> Bugfix for HomingMissileSpell

- core/src/main/java/com/nisovin/magicspells/spells/targeted/HealSpell.java
- Fixed an issue where `heal-percent` in `HealSpell` healed a percentage of missing health, rather than max health.
- Fixed an issue where `heal-percent` in `HealSpell` took the percentage to heal from the caster, instead of the target.
> Fix heal percent in HealSpell

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/Subspell.java
- core/src/main/java/com/nisovin/magicspells/spells/RandomSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/TargetedMultiSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/LoopSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigData.java
- The `interval` option of `LoopSpell` now supports values `<=0`. When `interval: 0` or less, all iterations of the loop are ran sequentially with no delay.
- Fixed an issue where `LoopSpell` could cancel twice if `duration` was used.
- `Subspell#subcast` now returns `SpellCastResult` instead of `CastResult`. This change also fixes several issues with spells that check if a subspell casts properly.
- The `pass-targeting` subspell cast argument now supports replacement. Additionally, if the value is set, the set value is now used regardless of the value of any spells with a `pass-targeting` option.
> Support an interval of 0 in LoopSpell, bugfixes

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/BlockBreakEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SilenceSpell.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/ParticleProjectileTracker.java
- Changed the default value of `notify-passive-spells` and `notify-helper-spells` in `SilenceSpell` to `true`, to match previous behavior.
- The `stage` option in the `blockbreak` spell effect now more closely matches the block destruction stage as specified in the [protocol](https://wiki.vg/Protocol#Set_Block_Destroy_Stage).
> Use Location#setDirection instead, change notify defaults

- build.gradle
- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/ModifierType.java
- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/TargetedMultiSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ReachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/BuildSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ExplodeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/MaterializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ZapSpell.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/util/SpellData.java
- core/src/main/java/com/nisovin/magicspells/util/SpellFilter.java
- core/src/main/resources/general.yml
- `ReachSpell`, `BuildSpell`, `MaterializeSpell`, and `ZapSpell` now use block data instead of material for playing break effects.
- Fixed an issue with the `power` and `addpower` modifier actions stripping some data in certain circumstances.
- Refactored `CastListener`. Now also listens for `PrePlayerAttackEntityEvent`, in order to process cast/cycle actions when attacking entities with `cast-on-animate: false`. Additionally, shooting will now only cast `BowSpell` spells.
- Fixed an issue with `TargetedMultiSpell` not properly considering failed targeting with `point-blank: false` and `require-entity-target: false`.
- The `reverse-bow-cycle-buttons` and `bow-cycle-spells-sneaking` options are now true by default.
- Fixed an issue where the damage of explosions caused by `ExplodeSpell` …
> Changes and bugfixes

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/util/config/FunctionData.java
- core/src/main/java/com/nisovin/magicspells/util/config/StringData.java
- Global variable and PAPI placeholders will now be resolved by non-player entities.
- Fixed an issue where `%targetpapi` placeholders used the caster instead of the target in `StringData`.
> Allow non-player entities to use global variables and PAPI

- core/src/main/java/com/nisovin/magicspells/util/trackers/ParticleProjectileTracker.java
- Use the pitch-adjusted `startLocation` instead of `from`.
> Fix pitch issue with particle projectiles

- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/FreezeTicksVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/MaxFireTicksVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/MaxFreezeTicksVariable.java
Added the `meta_freeze_tick`, `meta_max_freeze_ticks`, and `meta_max_fire_ticks` meta variables. Currently the max freeze/fire ticks aren't very useful, as the values are the same for all players, but may be used in the future whenever variables work for all living entities.
> Add freeze ticks, max freeze ticks and max fire ticks meta variables

- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/CaptureSpell.java
- core/src/main/java/com/nisovin/magicspells/util/MobUtil.java
- Use `ItemFactory` to determine an entity's egg material for `CaptureSpell`.
- No longer ignore cancelled drops when preventing casting from the arm swing caused by dropping items.
> Cleanup, bugfix

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/LookingAtBlockCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ReachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/SpellbookSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/BeamSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/BlockBeamSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/WallSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/BlinkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/BombSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/BuildSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/LoopSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/MaterializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/OrbitSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnTntSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SummonSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TelekinesisSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/VinesSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ZapSpell.java
- core/src/main/resources/general.yml
- Entity and block/location target checks now take into account accurate hitboxes and shapes of entities/blocks.
+ Added the `los-ray-size` option to `general.yml`. Defaults to `0.2`. Determines the size of the ray used for checking line of sight to entities when retrieving an entity target.
+ Added the `los-ignore-passable-blocks` option to `general.yml`. Defaults to `true`. When `true`, passable blocks (blocks that do not have any colliding parts that stop movement) are ignored for entity/location targeting. For example, air and tall grass are passable.
+ Added the `los-fluid-collision-mode` option to `general.yml`. Defaults to `never`, and has the values `always`, `never` and `source_only` as according to [here](https://jd.papermc.io/paper/1.20/org/bukkit/FluidCollisionMode.html). …
> Raytrace, cleanup

- .github/workflows/build.yml
- core/src/main/java/com/nisovin/magicspells/commands/MagicCommand.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ReachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ItemSerializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/BuildSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/util/CastItem.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/LoreHandler.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/PotionHandler.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/SkullHandler.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/WrittenBookHandler.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/alternative/AlternativeReaderManager.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/alternative/VanillaReader.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemData.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemDataParser.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItems.java
- The `title` and `author` options of magic items now support MiniMessage.
- Magic items now support the `external::vanilla` serialization type. This format for items is the same as the vanilla `/give` command.
- `ReachSpell` now supports placing blocks in blocks tagged as replaceable, instead of just air blocks.
- `BuildSpell` and `PulserSpell` now check if the block they attempt to set is placeable in the target location.
- The `potion-color` option of magic items has been replaced by the `color` option, for consistency.
- The `potion-data` option of magic items has been replaced by the `potion-type` option. The previous format, `<potion type> [extended/upgraded]`, is now just `<potion type>`, as extended/upgraded potion types are now their own, separate values.
- Fixed an issue where …
> Magic Item Adjustments, Bugfixes

- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemDataParser.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItems.java
- Allow `POTION_DATA` and `ENCHANTMENTS` to be valid values for the `ignored-attributes` and `blacklisted-attributes` magic item options.
> Check for more names

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/FireworksEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
- core/src/main/java/com/nisovin/magicspells/util/ParticleUtil.java
- `ParticleUtil` now also checks the particle registry for particle types.
- The totems and pulsers of `TotemSpell` and `PulserSpell` now tick individually. As such, the `interval` options on both spells now supports replacement.
- Fixed an issue that caused an error if `TotemSpell` could not find a targeted block.
- Fixed an issue that allowed `PulserSpell` to be broken normally in certain circumstances.
> Cleanup, TotemSpell and PulserSpell changes

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/EntityEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/MultiSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/VolleySpell.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- Added the `equipment` section to entity data. Supports the options `main-hand`, `off-hand`, `helmet`, `chestplate`, `leggings` and `boots`, which take a string-based magic item to equip the entity with in the options' respective equipment slot. Also supports the options `main-hand-drop-chance`, `off-hand-drop-chance`, `helmet-drop-chance`, `chestplate-drop-chance`, `leggings-drop-chance` and `boots-drop-chance`, which controls the drop chance for each slot.
- Fixed an issue where the `spread` and `speed` options of `VolleySpell` were not properly divided by 10.
- Fixed an issue with `MultiSpell` that caused an error when using a subspell containing a `:`.
- Fixed an issue where an error would occur if the `entity` effect did not spawn an entity due to invalid configuration.
- The …
> Entity data equipment support, bugfixes

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/AttributeBaseCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/AttributeCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/AttributeDefaultCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/LoopActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/OwnedLoopActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/PulserActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/TotemActiveCondition.java
- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/util/OperatorCondition.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/TotemSpell.java
- core/src/main/java/com/nisovin/magicspells/util/managers/ConditionManager.java
- Added the `attribute`, `attributebase` and `attributedefault` conditions. Each are operator conditions that check the value, base value and default value of the target's attributes, respectively.
- The `loopactive` and `ownedloopactive` conditions now allow optionally specifying an operator and value. Example: `loopactive loop-spell>1 denied`.
- Added the `totemactive` and `pulseractive` condition. Checks how many pulsers/totems the target has, respectively. Operator and value are optional. Examples: `totemactive totem-spell>4 denied`, `pulseractive pulser-spell required`.
> Attribute conditions, add operator support to loop conditions, add totemactive and pulseractive conditions

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/VariableStringEqualsCondition.java
- core/src/main/java/com/nisovin/magicspells/util/SpellUtil.java
- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/ExhaustionVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/SaturatedRegenRateVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/StarvationRateVariable.java
- core/src/main/java/com/nisovin/magicspells/variables/meta/UnsaturatedRegenRateVariable.java
- Allowed `variablestringequals` to use `=` for splitting instead of just `:`.
- Added `meta_exhaustion` (read [wiki](https://minecraft.wiki/w/Hunger#Mechanics)), `meta_starvation_rate`, `meta_saturated_regen_rate`, and `meta_unsaturated_regen_rate`.
> Add food regen meta variables

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/commands/MagicCommand.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/OrbitSpell.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/Interaction.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/ParticleProjectileTracker.java
- Fixed cooldown not persisting during reloads and restarts.
- `OrbitSpell` now has an `interactions` option for interacting with other orbits just like `ParticleProjectileSpell`. Interactions have been refactored such that they can be either configured as a list of strings like before or a list of configuration sections which allow for more configuration around each interaction:
* String: `<interactWith> <collisionSpell>` - The `<interactWith>` segment may now be a [string Spell Filter](https://github.com/TheComputerGeek2/MagicSpells/wiki/Spell-Filter#string).
* Config:
- `with`  - [Either variant of Spell Filter](https://github.com/TheComputerGeek2/MagicSpells/wiki/Spell-Filter)
- `collision-spell` - sub-spell to cast on collision.
- `stop-causing` (bool, `true` by default)
- …
> Config-based projectile interactions

- core/src/main/java/com/nisovin/magicspells/spells/targeted/PulserSpell.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/util/managers/VariableManager.java
- core/src/main/java/com/nisovin/magicspells/zones/NoMagicZoneWorldGuard.java
- Added the `interaction-height`, `interaction-width`, and `responsive` options to entity data for interaction entities.
- Fixed an issue that caused an error if the `namespace-key` option was not specified in the `boss-bar` section of a variable.
- Fixed an issue with the `worldguard` no magic zone type that caused zone checks to be incorrect if the region was re-defined.
> Additions and bugfixes

- README.md
- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/Spellbook.java
- core/src/main/java/com/nisovin/magicspells/commands/CommandHelpFilter.java
- core/src/main/java/com/nisovin/magicspells/commands/MagicCommand.java
- core/src/main/java/com/nisovin/magicspells/spells/CommandSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/AdminTeachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/BindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ForgetSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/HelpSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ImbueSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ItemSerializeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/KeybindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ListSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/ScrollSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/SpellbookSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/SublistSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/TeachSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/TomeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/command/UnbindSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/EnderchestSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/RecallSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SummonSpell.java
- core/src/main/java/com/nisovin/magicspells/util/TxtUtil.java
- towny/src/main/java/com/nisovin/magicspells/towny/MagicSpellsTowny.java
- Fixed some spells which accept spell names in their spell cast arguments not accepting internal spell names if the passed spell's `name` was defined. Full list: `BindSpell`, `ForgetSpell`, `HelpSpell`, `ImbueSpell`, `ScrollSpell`, `SpellbookSpell`, `TeachSpell`, `TomeSpell`, and `UnbindSpell`.
- Added cast command tab completion for spell cast arguments to: `AdminTeachSpell`, `BindSpell`, `ForgetSpell`, `HelpSpell`, `ImbueSpell`, `KeybindSpell`, `ListSpell`, `ScrollSpell`, `SpellbookSpell`, `SublistSpell`, `TeachSpell`, `TomeSpell`, `UnbindSpell`, `EnderchestSpell`, `RecallSpell`, and `SummonSpell`.
- Fixed the default yaw and pitch passed to the `/ms cast at` command from the executor's location being reversed.
- Added support for passing the `-p:` spell power flag and spell cast …
> Cast command tab completion

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticlesEffect.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- Only allow `equipment.body` for Mob entities.
- Fixed an issue that caused `ConfigDataUtil#getAngle` to not properly support `~` as a valid value.
- Renamed `color` in `ParticlesEffect` to `argb-color`, to avoid future name conflicts.
> Adjustments for Beta 15 release

- core/src/main/java/com/nisovin/magicspells/util/AttributeUtil.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/AttributeHandler.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/BannerHandler.java
- core/src/main/java/com/nisovin/magicspells/util/itemreader/alternative/VanillaReader.java
- core/src/main/java/com/nisovin/magicspells/util/magicitems/MagicItemData.java
- Breaking change: magic item comparison no longer uses a liberal method of attribute modifier checking. Attribute modifiers must now have the same ID and be listed in the same order in order to match.
- Attribute usages now allow specifying a full namespaced key.
- Fixed an issue that caused the `external::vanilla` magic item serializer to not output the correct format.
> More attribute changes, fix `external::vanilla` magic item serializer

- core/src/main/java/com/nisovin/magicspells/util/trackers/ParticleProjectileTracker.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/ProjectileTracker.java
- Fixed an issue with the `intermediate-effects` and `intermediate-hitboxes` options of `ParticleProjectileSpell` and `ProjectileSpell` that caused intermediate positions to be calculated improperly.
- Fixed an issue with the `intermeditate-hitboxes` option of `ProjectileSpell` that caused intermediate hits to continue to process after the projectile had stopped.
> Check intermediate hitboxes properly

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ModifyCooldownSpell.java
- core/src/main/java/com/nisovin/magicspells/util/config/StringData.java
- core/src/main/resources/plugin.yml
- Fixed Metrics Passive Listener chart.
- Grouped Metrics Reload Time chart with more readable slices.
- Removed alphanumeric (and `_`) limitation on default values of the `%arg` placeholder in spell messages and string expressions.
- Removed `[3, 16]` length limitation on player names in string expressions for the `%playervar` and `%playerpapi` placeholders.
- Fixed an issue where the `ModifyCooldownSpell` only worked if the spell was on cooldown.
> Metrics and Placeholder fixes

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/listeners/CastListener.java
- core/src/main/java/com/nisovin/magicspells/listeners/LeftClickListener.java
- core/src/main/java/com/nisovin/magicspells/listeners/RightClickListener.java
- core/src/main/resources/general.yml
Adds the `respect-item-cooldowns` option to `general.yml`. With `respect-item-cooldowns: true`, an item with a cooldown cannot be used to cast or cycle spells. Defaults to `false`.
> Add respect-item-cooldowns option

- core/src/main/java/com/nisovin/magicspells/spells/passive/util/PassiveListener.java
Lets passive spells with `helper-spell: true` be casted by any player.
> Check helper-spell for passives

- .github/workflows/wiki.yml
The `gollum` event provides a list of edited `pages` which provide a `summary` field, a `sha` of the commit, and other unrelated fields. The `summary` is supposed to be the wiki change commit message "subject", but instead it only provides the subject if the commit message "body" is present, which cannot be added through the web editor. However, the action throws an NPE if the summary field is populated.
```
subject
body
```
This PR checks the wiki repo to collect the subject and body of the committed page edits. Edits made through the web editor only affect one page. However, should someone with push access affect multiple pages, the action we used before this PR would send one embed per page edited in a single message, not considering the limit of 10 embeds per message. This PR sends …
> Wiki Alert compact & description fix

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/events/MagicSpellsEntityDamageByEntityEvent.java
- core/src/main/java/com/nisovin/magicspells/events/SpellApplyDamageEvent.java
- core/src/main/java/com/nisovin/magicspells/handlers/DeprecationHandler.java
- core/src/main/java/com/nisovin/magicspells/spells/PassiveSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/FlamewalkSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/InvulnerabilitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ResistSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ThrowBlockSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/DamageListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/FatalDamageListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/GiveDamageListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/TakeDamageListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/TicksListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/util/PassiveListener.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/CombustSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DamageSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DotSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/DrainlifeSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/FireballSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ForcetossSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/GeyserSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/LightningSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/PainSpell.java
- core/src/main/java/com/nisovin/magicspells/util/DeprecationNotice.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigData.java
- core/src/main/java/com/nisovin/magicspells/util/managers/PassiveManager.java
Closes #557.
- Added a section-based format for passive triggers. Old triggers do not currently have support for the format.
```yml
test:
spell-class: ".PassiveSpell"
triggers:
- trigger: <trigger name> # Specifies the type of the passive trigger.
priority: normal # Specifies the event priority of the passive trigger. Defaults to 'normal'.
```      
- Added the `damage` passive trigger.
```yml
test:
spell-class: ".PassiveSpell"
triggers:
- trigger: damage
mode: give # Specifies if this trigger fires for taking damage or receiving damage. Takes the values of 'give' or 'take'. Required.
damage-types: ["player_attack", "#bypasses_armor"] # List of damage types and damage type tags to listen for.
indirect-damager: true # If true, if the damage is indirect, the causing entity (i.e. an entity …
```
> Properly support damage types

- 3rd_party_licenses/LICENSE-Apache_v2
- 3rd_party_licenses/LICENSE-BDSv3
- 3rd_party_licenses/LICENSE-GPLv2
- 3rd_party_licenses/LICENSE-GPLv3
- 3rd_party_licenses/LICENSE-MIT
- 3rd_party_licenses/LICENSE-apache_math
- NOTICE.md
- README.md
- core/build.gradle
MagicSpells uses third-party software in ways in which it is obligated to include some of its licences and attributions depending on their license types and how they are linked:
- Dynamic linking is the usage of software which is installed separately.
- Static linking is redistributed software, such as shaded software.
MagicSpells does not modify any of its 3rd party software to make it a derivative of that software, it only uses their API. However, licenses such as GPL consider software a derivative even if no modifications are made. Plugins are not considered derivatives of PaperMC and don't have to follow its GPLv3 license (practically, but it is a legally gray area) because PaperMC serves as a loader and at "arm's length".
This PR includes all relevant copies of dependency licences in …
> Add 3rd party licenses

- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/listeners/MagicSpellListener.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/trackers/EffectTracker.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ParticleProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/instant/ProjectileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/OrbitSpell.java
- core/src/main/java/com/nisovin/magicspells/util/DelayableEntity.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/ParticleProjectileTracker.java
- core/src/main/java/com/nisovin/magicspells/util/trackers/ProjectileTracker.java
- Fixed an issue where playing the `entity` and `armorstand` effect with `delay` did not pass the spawned entities to spells which would remove them on reload or drag them along their path, such as orbits, projectiles, etc.
- Fixed an issue where the `HomingMissileSpell` was not cleaned up on plugin reload.
- Added support for the `armorstand` effect on the `ProjectileSpell`.
> Delayed "entity" and "armorstand" entity handling

- build.gradle
- buildSrc/src/main/java/dev/magicspells/gradle/MSPaperweight.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/SpellEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticleCloudEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticlesEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticlesPersonalEffect.java
- core/src/main/resources/plugin.yml
- gradle/wrapper/gradle-wrapper.properties
- nms/latest/build.gradle
- Added the `trail` section to the `particles` spell effect, for use with `particle-name: trail`.
```yml
test:
spell-class: ".targeted.AreaEffectSpell"
horizontal-radius: 16
vertical-radius: 8
spells:
- test/trail
test/trail:
spell-class: ".targeted.LoopSpell"
duration: 200
interval: 2
effects:
0:
position: caster
effect: particles
particle-name: trail
count: 2
height-offset: 0.5
trail:
origin: caster # Particle position. Specifies where the particles start. Defaults to 'POSITION'.
target: target # Particle position. Specifies where the particles travel to. Required.
color: # RGB color. Specifies the color of the trail particles. Required.
red: "rand(100, 255)"
green: "rand(100, 255)"
blue: "rand(100, 255)"
duration: 20 # Integer. Specifies how long the trail particles take to travel. …
```
> Add options for trail particle

- core/src/main/java/com/nisovin/magicspells/castmodifiers/conditions/HasItemCondition.java
- core/src/main/java/com/nisovin/magicspells/handlers/DeprecationHandler.java
It has been discussed internally that we would deprecate `hasitem` in favour of `hasitemprecise` for a while due to its old format being inconsistent across the plugin. Upon reviewing #369 I realised a multitude of bugs with `hasitem` that would not be worth fixing only to deprecate it later.
The modifier condition is supposed to check all slots, have item name and durability optional, and work with any entity or storage block. Instead, it requires the item name to be specified before it can check duration but incorrectly checks both. If only the material is specified, for players, it doesn't check extra slots like armor or offhand. For entities that don't have inventories, it only checks their hand item material.
Closes #369
> Deprecate "hasitem" modifier condition

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/spells/BuffSpell.java
- core/src/main/resources/general.yml
- Added the `real-time-duration` option to `.BuffSpell`. Defaults to `false`. When `true`, buffs are measured in real time rather than based on ticks.
- The `duration` option of `.BuffSpell` now supports replacement.
- Changed the default value of the `buff-check-interval` option in `general.yml` from `100` to `1`.
- Fixed an issue that prevented certain option types from functioning in `defaults.yml`.
> Support replacement for BuffSpell duration, default to tick based duration

- core/src/main/java/com/nisovin/magicspells/Subspell.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- core/src/main/java/com/nisovin/magicspells/util/config/VariableConfigData.java
- Fixed an issue where variable replacement for booleans used `false` for invalid values, instead of the supplied default value.
- Added the `pass-args` subspell cast argument. With `pass-args=true`, arguments from the parent spell cast are used for the subspell cast, instead of the value of the `args` subspell cast argument.
- The `invert` and `pass-power` subspell cast arguments now support replacement.
> Boolean replacement bugfix, subspell additions

- NOTICE.md
- buildSrc/src/main/java/dev/magicspells/gradle/MSJavaPlugin.java
- core/build.gradle
- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/GlowSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ext/GlowSpell.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- core/src/main/java/com/nisovin/magicspells/util/glow/impl/PacketEventsGlowManager.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/ManagerVolatile.java
- core/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeDisabled.java
- core/src/main/resources/general.yml
- core/src/main/resources/plugin.yml
- nms/latest/src/main/java/com/nisovin/magicspells/volatilecode/latest/VolatileCodeLatest.java
- nms/latest/src/main/java/com/nisovin/magicspells/volatilecode/latest/VolatileGlowManagerLatest.java
- nms/shared/build.gradle
- nms/shared/src/main/java/com/nisovin/magicspells/util/glow/GlowManager.java
- nms/shared/src/main/java/com/nisovin/magicspells/util/glow/LibsDisguiseHelper.java
- nms/shared/src/main/java/com/nisovin/magicspells/util/glow/PacketBasedGlowManager.java
- nms/shared/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeHandle.java
- nms/shared/src/main/java/com/nisovin/magicspells/volatilecode/VolatileCodeHelper.java
Adds `.targeted.GlowSpell`, a replacement for `.targeted.ext.GlowSpell`.
Example:
```yml
glow:
spell-class: ".targeted.GlowSpell"
key: example:glow # Specifies a namespaced key for the glow. Glows with the same key override each other. Supports replacement. Optional.
color: red # Specifies the glow's color. Optional.
global: true # Specifies whether the glow is only visible to the caster, or all players. Defaults to `true`.
duration: 200 # Specifies how long the glow should last, in ticks. Only applies when the value is greater than 0. Defaults to `0`.
priority: 20 # Specifies the priority of the glow. The glow with the highest priority will be applied. Defaults to `0`.
glow/remove:
spell-class: ".targeted.GlowSpell"
key: example:glow # Specifies the namespaced key of the glow to remove. …
```
> Add GlowSpell

- .github/workflows/pr_comment.yml
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ParticleCloudEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/MenuSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ParticleCloudSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/ReplaceSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/VolleySpell.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/util/Util.java
- core/src/main/java/com/nisovin/magicspells/util/config/ConfigDataUtil.java
- The `ParticleCloudSpell` option `potion-effects` now relies on the common [Potion Effects List](https://github.com/TheComputerGeek2/MagicSpells/wiki/Potion-Effect-List) format, which causes a minor breaking change in the string variant of the format (`<potion> <duration> <amplifier> <ambient> <particles> <icon>`), where `ambient` now refers toggles `hidden`, and `particles` now toggles `ambient`.
- The `particlecloud` spell effect can now utilise the `argb-color` option to color the `entity_effect` particle.
- Restored the `particle-name` option to `ParticleCloudSpell` as an alias to the `particle` option, as it was unintentionally renamed in `4.0 Beta 13`.
- Added [`potion-effects`](https://github.com/TheComputerGeek2/MagicSpells/wiki/Potion-Effect-List) to Entity Data.
- Added options …
> Particle Cloud Improvements

- core/src/main/java/com/nisovin/magicspells/spells/passive/HitArrowListener.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/MissArrowListener.java
- Properly use the weapon that fired the arrow, instead of the current main hand item, for the `hitarrow` and `missarrow` passive triggers.
- Properly check for arrow misses for the `missarrow` trigger.
> Properly check weapon item for `hitarrow` trigger

- core/src/main/java/com/nisovin/magicspells/spells/targeted/HomingMissileSpell.java
Take maximum between configured value and zero rather than minimum between the two.
> Fix intermediate special effects option in HomingMissileSpell to not always zero out the number of intermediate effects.

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/spells/ExternalCommandSpell.java
- core/src/main/java/com/nisovin/magicspells/util/config/StringData.java
- Adds `%a_uuid`, `%t_uuid`, and `%r_uuid` placeholders.
- The `ExternalCommandSpell` option `command-to-execute-later` can now use the rest of the placeholders.
> feat: Add UUID placeholders

- core/src/main/antlr/com/nisovin/magicspells/util/grammars/RegistryEntryPredicate.g4
- core/src/main/java/com/nisovin/magicspells/Spell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/InvulnerabilitySpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ResistSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/passive/DamageListener.java
- core/src/main/java/com/nisovin/magicspells/util/RegistryEntryPredicate.java
- core/src/main/java/com/nisovin/magicspells/util/grammars/RegistryEntryPredicateVisitorImpl.java
Currently used in `InvulnerabilitySpell`, `ResistSpell` and the `damage` trigger.
> Add predicate for registry entries

- core/src/main/java/com/nisovin/magicspells/MagicSpells.java
- core/src/main/java/com/nisovin/magicspells/zones/NoMagicZone.java
- core/src/main/resources/general.yml
- core/src/main/resources/spells-regular.yml
- core/src/main/resources/zones.yml
The default value for `ops-ignore-(reagents/cooldowns/cast-times)` in `general.yml` has been changed to `false`.
> Change "ops-ignore-" default to "false"

- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ArmorStandEffect.java
- core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/EntityEffect.java
- core/src/main/java/com/nisovin/magicspells/spells/MultiSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/MinionSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/buff/ext/DisguiseSpell.java
- core/src/main/java/com/nisovin/magicspells/spells/targeted/SpawnEntitySpell.java
- core/src/main/java/com/nisovin/magicspells/util/EntityData.java
- core/src/main/java/com/nisovin/magicspells/util/ai/goals/PathToGoal.java
- Added `minion` option to `MinionSpell` which accepts an [Entity Data](https://github.com/TheComputerGeek2/MagicSpells/wiki/Entity-Data) configuration section. Due to conflicts, if `minion` is used, `baby` has to be configured within it, not the spell option.
- New Entity Data options:
- [Nameable](https://jasperlorelai.eu/paperdocs/org.bukkit.entity/org/bukkit/class-use/Nameable.html):
- `custom-name` - [Rich Text](https://github.com/TheComputerGeek2/MagicSpells/wiki/Expression#rich-text)
- [Entity](https://jasperlorelai.eu/paperdocs/org.bukkit.entity/org/bukkit/entity/class-use/Entity.html):
- `custom-name-visible` - Boolean
- `item`:
- `item` - [Vanilla item format](https://minecraft.wiki/w/Argument_types#item_stack) or [Magic Item …
> Entity Data fixes
